juego:
  pantalla:
    ancho: 800
    alto: 550
  parametros:
    margen_scroll: 150
  tiposProtagonista:
    Charmeleon:
      ancho: 65
      alto: 73
      vel_personaje: 300
      salto: 100
      animaciones:
        quieto:
          sprites: src/resources/charmeleonQuieto.bmp
        caminar:
          sprites: src/resources/charmeleonMovimiento.bmp
        saltar:
          sprites: src/resources/charmeleonQuieto.bmp
    mono:
      ancho: 140
      alto: 126
      vel_personaje: 300
      salto: 100
      animaciones:
        quieto:
          sprites: src/resources/gokumonoQuieto.bmp
        caminar:
          sprites: src/resources/gokumonoGritando.bmp
        saltar:
          sprites: src/resources/charmeleonQuieto.bmp
    Goku:
      ancho: 65
      alto: 73
      vel_personaje: 300
      salto: 100
      animaciones:
        quieto:
          sprites: src/resources/charmeleonQuieto.bmp
        caminar:
          sprites: src/resources/charmeleonMovimiento.bmp
        saltar:
          sprites: src/resources/charmeleonQuieto.bmp
  tiposAutomatico:  
    mono:
      ancho: 140
      alto: 126
      animaciones:
        quieto:
          sprites: src/resources/gokumonoQuieto.bmp
          periodo:
        caminar:
          sprites: src/resources/gokumonoGritando.bmp
          periodo: 3
        grito2:
          sprites: src/resources/gokumonoMovimiento.bmp
          periodo: 2
    princesa:
      ancho: 55
      alto: 47
      animaciones:
        quieto:
          sprites: src/resources/pikachuQuieto.bmp
          periodo: 2
        ayudenme:
          sprites: src/resources/pikachuMovimiento.bmp
          periodo: 7
  texturas:
    viga: src/resources/viga2.jpg
    esc: src/resources/film.png
  nivel:
    - nivel: MooMooMilk
      alto: 600
      ancho: 1600
      fondo: src/resources/fondoGrande.png
      personajes:
        - tipo: mono
          x: 100
          y: 150
        - tipo: princesa
          x: 700
          y: 150
        - tipo: princesa
          x: 700
          y: 599
      plataformas:
        - textura: viga
          x: 20
          y: 150
          ancho: 200
          alto: 50
        - textura: viga
          x: 550
          y: 150
          ancho: 200
          alto: 50
      escaleras:
        - textura: esc
          x: 1200
          y: 200
          ancho: 80
          alto: 400
    - nivel: Moo la Moo
      alto: 600
      ancho: 1600
      fondo: src/resources/viga2.jpg
      personajes:
        - tipo: protagonista
          x: 400
          y: 300
    - nivel: CUCU
      alto: 600
      ancho: 1600
      fondo: src/resources/fondoGrande.png
      personajes:
        - tipo: protagonista
          x: 400
          y: 300

