juego:
#  pantalla:
#    ancho: 1000
#    alto: 550
  parametros:
    margen_scroll: 100
  tiposProtagonista:
    Charmander:
      ancho: 65
      alto: 73
      vel_personaje: 12
      salto: 30
      animaciones:
        quieto:
          sprites: src/resources/cuerpos/Charmander/charmanderQuieto.bmp
          sonido: 
        caminar:
          sprites: src/resources/cuerpos/Charmander/charmanderMovimiento.bmp
          sonido: src/resources/cuerpos/footstep.ogg
        saltar:
          sprites: src/resources/cuerpos/Charmander/charmanderSalto.bmp
          sonido: src/resources/cuerpos/Yoshi/Yoshi-jump-2.ogg
      bolaDeFuego:
        ancho: 25
        alto: 20
        salto: 20
        animacion: src/resources/items/lanzallamas.bmp
    Yoshi:
      ancho: 52
      alto: 70
      vel_personaje: 10
      salto: 55
      animaciones:
        quieto:
          sprites: src/resources/cuerpos/Yoshi/Yoshi-Iddle.bmp
          sonido:
        caminar:
          sprites: src/resources/cuerpos/Yoshi/Yoshi-Walking.bmp
          sonido: src/resources/cuerpos/footstep.ogg
        saltar:
          sprites: src/resources/cuerpos/Yoshi/Yoshi-Jump.bmp
          sonido: src/resources/cuerpos/Yoshi/Yoshi-jump-3.ogg
      bolaDeFuego:
        ancho: 25
        alto: 25
        salto: 30
        animacion: src/resources/items/huevos.bmp
    Totodile:
      ancho: 61
      alto: 74
      vel_personaje: 10
      salto: 30
      animaciones:
        quieto:
          sprites: src/resources/cuerpos/Totodile/totodileQuieto.bmp
          sonido:
        caminar:
          sprites: src/resources/cuerpos/Totodile/totodileMovimiento.bmp
          sonido: src/resources/cuerpos/footstep.ogg
        saltar:
          sprites: src/resources/cuerpos/Totodile/totodileSalto.bmp
          sonido: 
      bolaDeFuego:
        ancho: 22
        alto: 22
        salto: 30
        animacion: src/resources/items/chorroDeAgua.bmp
    Gengar:
      ancho: 55
      alto: 55
      vel_personaje: 30
      salto: 30
      sonido: 
      animaciones:
        quieto:
          sprites: src/resources/cuerpos/Gengar/gengarQuieto.bmp
          sonido: 
        caminar:
          sprites: src/resources/cuerpos/Gengar/gengarMovimiento.bmp
          sonido: src/resources/cuerpos/footstep.ogg
        saltar:
          sprites: src/resources/cuerpos/Gengar/gengarSalto.bmp
          sonido: src/resources/cuerpos/Gengar/Gengar-jump.ogg
      bolaDeFuego:
        ancho: 40
        alto: 25
        salto: 20
        animacion: src/resources/items/bolaSombra.bmp
    Pikachu:
      ancho: 73
      alto: 66
      vel_personaje: 25
      salto: 25
      sonido: 
      animaciones:
        quieto:
          sprites: src/resources/cuerpos/Pikachu/pikachuQuieto2.bmp
          sonido: 
        caminar:
          sprites: src/resources/cuerpos/Pikachu/pikachuMovimiento2.bmp
          sonido: src/resources/cuerpos/footstep.ogg
        saltar:
          sprites: src/resources/cuerpos/Pikachu/pikachuSalto.bmp
          sonido: 
      bolaDeFuego:
        ancho: 51
        alto: 24
        salto: 8
        animacion: src/resources/items/thundershock.bmp
  tiposAutomatico:  
    troll:
      ancho: 200
      alto: 200
      animaciones:
        quieto:
          sprites: src/resources/trollface.bmp
          sonido:
          periodo: 2
        ayudenme:
          sprites: src/resources/trollface.bmp
          sonido:
          periodo: 7
  princesa:
    ancho: 62
    alto: 54
    velocidad: 5
    animaciones:
      quieto: src/resources/cuerpos/Primeape/primeapeQuieto.bmp
      gritando: src/resources/cuerpos/Primeape/primeapeMovimiento.bmp
  mono:
    ancho: 140
    alto: 126
    velocidad: 10
    animaciones:
      quieto: src/resources/cuerpos/GokuMono/gokumonoQuieto.bmp
      lanzando: src/resources/cuerpos/GokuMono/gokumonoGritando.bmp
  barril:
    ancho: 54
    alto: 46
    velocidad: 10
    animaciones:
      cayendo: src/resources/items/barril-falling.bmp
      quieto: src/resources/items/barril-rodando.bmp
      rodando: src/resources/items/barril-rodando.bmp
      bajando: src/resources/items/barril-falling.bmp
  tortuga:
    ancho: 40
    alto: 40
    velocidad: 7
    animaciones:
      saltando: src/resources/cuerpos/Squirtle/squirtleMovimiento.bmp
      quieto: src/resources/cuerpos/Squirtle/squirtleMuerto.bmp
      caminando: src/resources/cuerpos/Squirtle/squirtleMovimiento.bmp
      movil: src/resources/cuerpos/Squirtle/squirtleGirando.bmp
  hongo:
    ancho: 36
    alto: 35
    velocidad: 3
    animaciones:
      caminando: src/resources/items/shroomishMovimiento.bmp
      cayendo: src/resources/items/shroomishCaida.bmp
  vidaExtra:
    ancho: 50
    alto: 49
    velocidad: 2
    animaciones:
      movimiento: src/resources/items/rareCandy.bmp
  piedraEvolucion:
    ancho: 40
    alto: 40
    velocidad: 2
    animaciones:
      movimiento: src/resources/items/piedras.bmp
  activaEspecial:
    ancho: 55
    alto: 55
    velocidad: 5
    animaciones:
      movimiento: src/resources/items/fireball.bmp
  invencibilidad:
    ancho: 30
    alto: 30
    velocidad: 5
    animaciones:
      movimiento: src/resources/items/Pluma.bmp
  tuberias:
    tuberiaHongo:
      ancho: 30
      alto: 30
      probabilidades:
        hongo: 100
      animaciones:
        abajo: src/resources/items/tuberia3.bmp
        arriba: src/resources/items/tuberia.bmp
        derecha: src/resources/items/tuberia2.bmp
        izquierda: src/resources/items/tuberia4.bmp
    tuberiaTortuga:
      ancho: 30
      alto: 30
      probabilidades:
        tortuga: 100
      animaciones:
        abajo: src/resources/items/tuberia3.bmp
        arriba: src/resources/items/tuberia.bmp
        derecha: src/resources/items/tuberia2.bmp
        izquierda: src/resources/items/tuberia4.bmp
    tuberiaHT:
      ancho: 60
      alto: 60
      probabilidades:
        hongo: 100
        tortuga: 100
      animaciones:
        abajo: src/resources/items/tuberia3.bmp
        arriba: src/resources/items/tuberia.bmp
        derecha: src/resources/items/tuberia2.bmp
        izquierda: src/resources/items/tuberia4.bmp
  texturas:
    viga: src/resources/items/viga2.jpg
    esc: src/resources/items/film.png
  nivel:
    - nivel: MooMooMilk
      players: 2
      alto: 600
      ancho: 1600
      piso: 540
      fondo: src/resources/fondoGrande.png
      musica: src/resources/niveles/route1.ogg
      elementos:
      #  - tipo: mono
     #     x: 100
    #      y: 150
        - tipo: princesa
          x: 600
          y: 150
        - tipo: mono
          x: 650
          y: 150
  #      - tipo: princesa
 #         x: 700
#          y: 599
      tuberias:
#        - tipo: tuberiaHongo
#          x: 200
#          y: 400
#          direccion: abajo
#          eme: 5
#        - tipo: tuberiaTortuga
#          x: 500
#          y: 550
#          direccion: arriba
#          eme: 5
        - tipo: tuberiaHT
          x: 500
          y: 350
          direccion: arriba
          eme: 5
      plataformas:
        - textura: viga
          x: 250
          y: 150
          ancho: 400
          alto: 50
        - textura: viga
          x: 300
          y: 350
          ancho: 400
          alto: 50
      vigas:
        - textura: viga
          x: 680
          y: 350
          ancho: 500
          alto: 50
          inclinacion: -20
      escaleras:
        - textura: esc
          x: 400
          y: 150
          ancho: 50
          alto: 200
        - textura: esc
          x: 600
          y: 350
          ancho: 50
          alto: 200
    - nivel: cUCU
      players: 1
      alto: 2560
      ancho: 1600
      fondo: src/resources/ph-101661.jpg
      musica: src/resources/niveles/route1.ogg
      piso: 2450
      elementos:
        - tipo: princesa
          x: 600
          y: 150
        - tipo: mono
          x: 650
          y: 150
      tuberias:
        - tipo: tuberiaHT
          x: 200
          y: 2140
          direccion: arriba
          eme: 5
        - tipo: tuberiaHongo
          x: 800
          y: 2200
          direccion: abajo
          eme: 5
        - tipo: tuberiaHT
          x: 800
          y: 380
          direccion: derecha
          eme: 5
      plataformas:
        - textura: viga
          x: 450
          y: 150
          ancho: 200
          alto: 50
        - textura: viga
          x: 10
          y: 540
          ancho: 300
          alto: 50
        - textura: viga
          x: 380
          y: 350
          ancho: 400
          alto: 50
        - textura: viga
          x: 90
          y: 2130
          ancho: 1300
          alto: 50
        - textura: viga
          x: 0
          y: 2400
          ancho: 1600
          alto: 50
        - textura: viga
          x: 700
          y: 1135
          ancho: 200
          alto: 50
        - textura: viga
          x: 400
          y: 1135
          ancho: 200
          alto: 50
      vigas:
        - textura: viga
          x: 700
          y: 330
          ancho: 500
          alto: 50
          inclinacion: 20
      escaleras:
        - textura: esc
          x: 800
          y: 1135
          ancho: 50
          alto: 1000
        - textura: esc
          x: 435
          y: 135
          ancho: 50
          alto: 1000
        - textura: esc
          x: 600
          y: 2130
          ancho: 50
          alto: 270
    - nivel: Troll
      players: 4
      alto: 600
      ancho: 1600
      piso: 540
      fondo: src/resources/fondoGrande.png
      musica: src/resources/niveles/trololo.ogg
      personajes:
        - tipo: troll
          x: 100
          y: 150
        - tipo: troll
          x: 700
          y: 150
        - tipo: troll
          x: 700
          y: 599
      plataformas:
        - textura: viga
          x: 250
          y: 150
          ancho: 200
          alto: 50
        - textura: viga
          x: 500
          y: 450
          ancho: 50
          alto: 50
        - textura: viga
          x: 550
          y: 430
          ancho: 50
          alto: 50
        - textura: viga
          x: 600
          y: 410
          ancho: 50
          alto: 50
        - textura: viga
          x: 650
          y: 390
          ancho: 50
          alto: 50
        - textura: viga
          x: 700
          y: 370
          ancho: 50
          alto: 50
        - textura: viga
          x: 750
          y: 350
          ancho: 50
          alto: 50
      escaleras:
        - textura: esc
          x: 100
          y: 150
          ancho: 80
          alto: 400
    - nivel: Moo la Moo
      players: 3
      alto: 1200
      ancho: 1200
      fondo: src/resources/items/viga2.jpg
      musica:
      personajes:
        - tipo: princesa
          x: 400
          y: 300
