juego:
#  pantalla:
#    ancho: 1000
#    alto: 550
  parametros:
    margen_scroll: 40
  tiposProtagonista:
    Charmander:
      ancho: 65
      alto: 73
      vel_personaje: 12
      salto: 30
      animaciones:
        quieto:
          sprites: src/resources/charmanderQuieto.bmp
          sonido:
        caminar:
          sprites: src/resources/charmanderMovimiento.bmp
          sonido: 
        saltar:
          sprites: src/resources/charmanderSalto.bmp
          sonido: rutaSonidoChar
    Yoshi:
      ancho: 52
      alto: 70
      vel_personaje: 10
      salto: 55
      animaciones:
        quieto:
          sprites: src/resources/cuerpos/Yoshi/Yoshi-Iddle.bmp
          sonido:
        caminar:
          sprites: src/resources/cuerpos/Yoshi/Yoshi-Walking.bmp
          sonido:
        saltar:
          sprites: src/resources/cuerpos/Yoshi/Yoshi-Jump.bmp
          sonido: rutaSonidoYoshi
    Mono:
      ancho: 140
      alto: 126
      vel_personaje: 10
      salto: 50
      sonido: rutaSonidoMono
      animaciones:
        quieto:
          sprites: src/resources/gokumonoQuieto.bmp
          sonido:
        caminar:
          sprites: src/resources/gokumonoMovimiento.bmp
          sonido:
        saltar:
          sprites: src/resources/gokumonoSalto.bmp
          sonido: rutaSonidoMono
    Gengar:
      ancho: 55
      alto: 55
      vel_personaje: 30
      salto: 30
      sonido: rutaSonidoGengar
      animaciones:
        quieto:
          sprites: src/resources/gengarQuieto.bmp
        caminar:
          sprites: src/resources/gengarMovimiento.bmp
        saltar:
          sprites: src/resources/gengarSalto.bmp
  tiposAutomatico:  
    mono:
      ancho: 140
      alto: 126
      animaciones:
        quieto:
          sprites: src/resources/gokumonoQuieto.bmp
          sonido:
          periodo:
        caminar:
          sprites: src/resources/gokumonoGritando.bmp
          sonido:
          periodo: 3
        grito2:
          sprites: src/resources/gokumonoMovimiento.bmp
          sonido:
          periodo: 2
    princesa:
      ancho: 55
      alto: 47
      animaciones:
        quieto:
          sprites: src/resources/pikachuQuieto.bmp
          sonido:
          periodo: 2
        ayudenme:
          sprites: src/resources/pikachuMovimiento.bmp
          sonido:
          periodo: 7
  texturas:
    viga: src/resources/viga2.jpg
    esc: src/resources/film.png
  nivel:
    - nivel: MooMooMilk
      alto: 600
      ancho: 1600
      piso: 540
      fondo: src/resources/fondoGrande.png
      musica: 
      personajes:
        - tipo: mono
          x: 100
          y: 150
        - tipo: princesa
          x: 700
          y: 150
        - tipo: princesa
          x: 700
          y: 599
      plataformas:
        - textura: viga
          x: 250
          y: 150
          ancho: 200
          alto: 50
        - textura: viga
          x: 750
          y: 350
          ancho: 50
          alto: 50
        - textura: viga
          x: 700
          y: 370
          ancho: 50
          alto: 50
        - textura: viga
          x: 650
          y: 390
          ancho: 50
          alto: 50
        - textura: viga
          x: 600
          y: 410
          ancho: 50
          alto: 50
        - textura: viga
          x: 550
          y: 430
          ancho: 50
          alto: 50
        - textura: viga
          x: 500
          y: 450
          ancho: 50
          alto: 50
      escaleras:
        - textura: esc
          x: 100
          y: 150
          ancho: 80
          alto: 400
    - nivel: Moo la Moo
      alto: 1200
      ancho: 1200
      fondo: src/resources/viga2.jpg
      musica:
      personajes:
        - tipo: princesa
          x: 400
          y: 300
    - nivel: CUCU
      alto: 600
      ancho: 800
      fondo: src/resources/fondoGrande.png
      musica:
      personajes:
        - tipo: mono
          x: 400
          y: 300
