juego:
  pantalla:
    ancho: 800
    alto: 700
    fondo: src/resources/fondoGrande.png
  parametros:
    vel_personaje: 400
    margen_scroll: 80
  tiposProtagonista:
    protagonista:
      ancho: 65
      alto: 73
      animaciones:
        quieto:
          sprites: src/resources/charmeleonQuieto.bmp
        caminar:
          sprites: src/resources/charmeleonMovimiento.bmp
        saltar:
          sprites: src/resources/charmeleonQuieto.bmp
    defe:
      ancho: 55
      alto: 47
      animaciones:
        quieto:
          sprites: src/resources/pikachuQuieto.bmp
        caminar:
          sprites: src/resources/pikachuMovimiento.bmp
  tiposAutomatico:
    mono:
      ancho: 62
      alto: 54
      animaciones:
        quieto:
          sprites: src/resources/primeapeQuieto.bmp
        grito:
          sprites: src/resources/primeapeMovimiento.bmp
          periodo: 10
    princesa:
      ancho: 55
      alto: 47
      animaciones:
        quieto:
          sprites: src/resources/pikachuQuieto.bmp
        ayudenme:
          sprites: src/resources/pikachuMovimiento.bmp
          periodo: 7
    defe:
      ancho: 55
      alto: 47
      animaciones:
        quieto:
          sprites: src/resources/pikachuQuieto.bmp
        ayudenme:
          sprites: src/resources/pikachuMovimiento.bmp
          periodo: 7
  texturas:
    viga: src/resources/viga2.jpg
    esc: src/resources/film.png
    defe: src/resources/viga2.jpg
  nivel:
    alto: 700
    ancho: 1400
    personajes:
      - tipo: protagonista
        x: 40
        y: 486
      - tipo: mono
        x: 250
        y: 156
      - tipo: princesa
        x: 940
        y: 286
    plataformas:
      - textura: viga
        x: 0
        y: 482
        ancho: 2000
        alto: 120
      - textura: viga
        x: 200
        y: 152
        ancho: 400
        alto: 50
    escaleras:
      - textura: esc
        x: 900
        y: 282
        ancho: 100
        alto: 100

